[package]
name = "mongodb-schema-parser"
version = "0.1.0"
license = "Apache-2.0"
repository = "https://github.com/lrlna/mongodb-schema-parser"
documentation = "https://docs.rs/mongodb-schema-parser"
description = "MongoDB Schema Analysis"
authors = ["Irina Shestak <shestak.irina@gmail.com>"]
readme = "README.md"
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
failure = "0.1.2"
serde = "^1.0.59"
serde_json = "^1.0.38"
serde_derive = "^1.0.59"
bson = { git = "https://github.com/lrlna/bson-rs", branch = "wasm-suport" } 
wee_alloc = "0.4.2"
console_error_panic_hook = "0.1.5"
js-sys = "0.3.16"
web-sys = { version = "0.3.16", features = ['console'] }

[dependencies.wasm-bindgen]
version = "^0.2.37"
features = ["serde-serialize"]
