[package]
name = "mongodb-schema"
version = "0.1.0"
license = "Apache-2.0"
repository = "https://github.com/lrlna/mongodb-schema"
documentation = "https://docs.rs/mongodb-schema"
description = "MongoDB Schema Analysis"
authors = ["Irina Shestak <shestak.irina@gmail.com>"]
readme = "README.md"

[lib]
crate-type = ["cdylib"]

[dependencies]
failure = "0.1.2"
wasm-bindgen="0.2"

[dev-dependencies]
